using System.Collections.Generic;
using RimWorld;
using Verse;

namespace AsAboveSoBelow
{
    /// <summary>
    /// The basement "environment" registry: what a newly generated basement
    /// level becomes. Backs the single Generation-tab selector
    /// (ABSettings.basementType) and is read by the basement gensteps.
    ///
    /// Stored values:
    ///  - "SolidRock"  : default vanilla mineable-rock fill (no carve).
    ///  - "Caverns"    : a Biomes! Caverns living cavern; the specific biome is
    ///                   cavernBiome and the BC-only stalagmite/crystal dressing
    ///                   runs. Offered only when Biomes! Caverns is loaded.
    ///  - "UrbanRuins" : an Ancient urban ruins prefab facility stamped into the
    ///                   rock (AncientUrbanRuinsCompat). Offered only when
    ///                   Ancient urban ruins is loaded.
    ///  - a BiomeDef defName from ForeignCarveBiomes : the generalized worm
    ///                   carve, floored/planted/populated from that biome.
    ///                   Offered only when the biome def is present.
    ///
    /// Caverns and the foreign biomes share one mechanism (GenStep_ABCavernCarve);
    /// UrbanRuins is a distinct prefab-stamp mechanism (GenStep_ABUrbanRuins).
    /// Everything fails open to solid rock.
    /// </summary>
    public static class BasementEnv
    {
        public const string SolidRock = "SolidRock";
        public const string Caverns = "Caverns";
        public const string UrbanRuins = "UrbanRuins";

        /// <summary>Curated surface biomes that read well as a sealed basement.
        /// Each appears in the selector only when its BiomeDef is present (its
        /// source mod is loaded). Temperature caveat: pocket maps use the
        /// biome's fixed temperature, so extreme biomes make harsh basements.</summary>
        public static readonly string[] ForeignCarveBiomes =
        {
            "AB_MycoticJungle",           // Alpha Biomes - fungal cavern (best fit)
            "AB_GelatinousSuperorganism", // Alpha Biomes - living flesh sublevel
            "AB_RockyCrags",              // Alpha Biomes - forsaken crags, raw rock
            "AB_TarPits"                  // Alpha Biomes - oily industrial sump
        };

        public struct Option
        {
            public string id;
            public string label;
        }

        public static bool IsForeignCarve(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return false;
            }
            for (int i = 0; i < ForeignCarveBiomes.Length; i++)
            {
                if (ForeignCarveBiomes[i] == id)
                {
                    return DefDatabase<BiomeDef>.GetNamedSilentFail(id) != null;
                }
            }
            return false;
        }

        /// <summary>True when the type is generated by the worm carve (Biomes!
        /// Caverns or a curated foreign biome), as opposed to solid rock or the
        /// urban-ruins prefab stamp.</summary>
        public static bool IsCarveType(string id) => id == Caverns || IsForeignCarve(id);

        /// <summary>The BiomeDef a carve-type basement should use, or null when
        /// the type is not a carve.</summary>
        public static BiomeDef ResolveCarveBiome(ABSettings settings)
        {
            if (settings == null)
            {
                return null;
            }
            if (settings.basementType == Caverns)
            {
                return BiomesCavernsCompat.Resolve(settings.cavernBiome);
            }
            if (IsForeignCarve(settings.basementType))
            {
                return DefDatabase<BiomeDef>.GetNamedSilentFail(settings.basementType);
            }
            return null;
        }

        public static string LabelFor(string id)
        {
            if (id == SolidRock)
            {
                return "AB_BasementSolidRock".Translate();
            }
            if (id == Caverns)
            {
                return "AB_BasementCaverns".Translate();
            }
            if (id == UrbanRuins)
            {
                return "AB_BasementUrbanRuins".Translate();
            }
            BiomeDef b = DefDatabase<BiomeDef>.GetNamedSilentFail(id);
            return b != null ? b.LabelCap.ToString() : id;
        }

        /// <summary>Every basement environment currently offerable, in menu order.</summary>
        public static List<Option> AvailableOptions()
        {
            List<Option> list = new List<Option>
            {
                new Option { id = SolidRock, label = LabelFor(SolidRock) }
            };
            if (BiomesCavernsCompat.Active)
            {
                list.Add(new Option { id = Caverns, label = LabelFor(Caverns) });
            }
            if (AncientUrbanRuinsCompat.Active)
            {
                list.Add(new Option { id = UrbanRuins, label = LabelFor(UrbanRuins) });
            }
            for (int i = 0; i < ForeignCarveBiomes.Length; i++)
            {
                string id = ForeignCarveBiomes[i];
                if (DefDatabase<BiomeDef>.GetNamedSilentFail(id) != null)
                {
                    list.Add(new Option { id = id, label = LabelFor(id) });
                }
            }
            return list;
        }

        /// <summary>Fold a stored type that is no longer offerable (its mod was
        /// removed) back to solid rock, so gen and UI never act on a dead id.</summary>
        public static string Sanitize(string id)
        {
            if (id == SolidRock)
            {
                return id;
            }
            if (id == Caverns)
            {
                return BiomesCavernsCompat.Active ? id : SolidRock;
            }
            if (id == UrbanRuins)
            {
                return AncientUrbanRuinsCompat.Active ? id : SolidRock;
            }
            return IsForeignCarve(id) ? id : SolidRock;
        }
    }
}
