#!/usr/bin/env bash
# generate-helicopter-view.sh
# ---------------------------------------------------------------------------
# Concatenates the ENTIRE As-above-So-below codebase into a single Markdown
# file for "helicopter view" chats: paste docs/HELICOPTER_VIEW.md into a fresh
# AI conversation to discuss the whole project's structure at once.
#
# Output:  docs/HELICOPTER_VIEW.md   (gitignored — it's a regenerable artifact)
# Usage:   bash docs/generate-helicopter-view.sh
#          (run from the mod root, or anywhere — it locates the root itself)
#
# What it includes: all .cs, all Defs/Patches/Languages XML, About.xml,
# ARCHITECTURE.md, and the project layout. What it skips: obj/ bin/ .git/,
# binaries (.dll .png .ogg), and this script's own output.
# ---------------------------------------------------------------------------
set -euo pipefail

# Resolve mod root = parent of this script's docs/ folder.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

OUT="docs/HELICOPTER_VIEW.md"
MOD_NAME="$(grep -oiP '(?<=<name>).*?(?=</name>)' About/About.xml 2>/dev/null | head -1 || echo 'RimWorld mod')"

# Ordered globs. Docs first (context), then C# by module, then XML content.
mapfile -t FILES < <(
  {
    printf '%s\n' ARCHITECTURE.md About/About.xml 2>/dev/null
    find Source -name '*.cs' -not -path '*/obj/*' -not -path '*/bin/*' 2>/dev/null | sort
    find Defs Patches Languages -name '*.xml' 2>/dev/null | sort
  } | awk 'NF && !seen[$0]++'   # de-dupe, drop blanks, preserve order
)

lang_for() {
  case "$1" in
    *.cs)  echo csharp ;;
    *.xml) echo xml ;;
    *.md)  echo markdown ;;
    *.sh)  echo bash ;;
    *)     echo text ;;
  esac
}

total_lines=0
{
  echo "# ${MOD_NAME} — Helicopter View (whole-codebase snapshot)"
  echo
  echo "> Auto-generated by \`docs/generate-helicopter-view.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')."
  echo "> Paste this whole file into a fresh chat for high-level structural conversations."
  echo "> **Do not hand-edit** — regenerate instead. For the curated map, read \`ARCHITECTURE.md\`."
  echo
  echo "## File index"
  echo
  for f in "${FILES[@]}"; do
    [ -f "$f" ] || continue
    lc=$(wc -l < "$f" | tr -d ' ')
    printf -- '- `%s` (%s lines)\n' "$f" "$lc"
  done
  echo
  echo "---"
  echo
  for f in "${FILES[@]}"; do
    [ -f "$f" ] || continue
    lc=$(wc -l < "$f" | tr -d ' ')
    total_lines=$((total_lines + lc))
    echo "## \`$f\`"
    echo
    echo "\`\`\`$(lang_for "$f")"
    cat "$f"
    echo "\`\`\`"
    echo
  done
} > "$OUT"

bytes=$(wc -c < "$OUT" | tr -d ' ')
files=${#FILES[@]}
concat_lines=$(wc -l < "$OUT" | tr -d ' ')
echo "Wrote $OUT"
echo "  files concatenated : $files"
echo "  output lines       : $concat_lines"
echo "  output size        : $(awk "BEGIN{printf \"%.1f KB\", $bytes/1024}")"
